services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: w10-dashboard:latest
    container_name: w10-dashboard
    restart: unless-stopped

    env_file:
      - .env

    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0

    networks:
      - proxy
      - database

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O - http://127.0.0.1:3000/ >/dev/null || exit 1"
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s


networks:
  proxy:
    external: true
    name: proxy

  database:
    external: true
    name: postgresql_default
